const questionsData = [
    { q: "Quelle est la capitale de la France ?", a: ["Lyon", "Marseille", "Paris", "Bordeaux"], r: 2 },
    { q: "Qui a peint la Joconde ?", a: ["Van Gogh", "Monet", "De Vinci", "Picasso"], r: 2 },
    { q: "Quelle planète est la plus proche du Soleil ?", a: ["Terre", "Mercure", "Mars", "Jupiter"], r: 1 },
    { q: "Combien de continents y a-t-il sur Terre ?", a: ["5", "6", "7", "8"], r: 2 },
    { q: "Quel est l'océan le plus vaste du monde ?", a: ["Atlantique", "Indien", "Arctique", "Pacifique"], r: 3 },
    { q: "En quelle année a eu lieu la Révolution française ?", a: ["1789", "1492", "1914", "1515"], r: 0 },
    { q: "Quel pays a la forme d'une botte ?", a: ["Espagne", "Italie", "Grèce", "Portugal"], r: 1 },
    { q: "Quel est le plus grand mammifère du monde ?", a: ["L'éléphant", "Le requin baleine", "La baleine bleue", "La girafe"], r: 2 },
    { q: "Qui a écrit 'Les Misérables' ?", a: ["Émile Zola", "Victor Hugo", "Albert Camus", "Molière"], r: 1 },
    { q: "Quel gaz les humains respirent-ils pour vivre ?", a: ["Le dioxyde de carbone", "L'azote", "L'oxygène", "L'hydrogène"], r: 2 },
    { q: "Quelle est la capitale du Japon ?", a: ["Kyoto", "Osaka", "Tokyo", "Seoul"], r: 2 },
    { q: "Quel est l'element chimique dont le symbole est 'Au' ?", a: ["Argent", "Cuivre", "Or", "Aluminium"], r: 2 },
    { q: "Combien de cotes possede un hexagone ?", a: ["5", "6", "7", "8"], r: 1 },
    { q: "Quel fleuve traverse l'Egypte ?", a: ["L'Amazone", "Le Nil", "Le Mississippi", "Le Danube"], r: 1 },
    { q: "Qui a decouvert l'Amerique en 1492 ?", a: ["Marco Polo", "Vasco de Gama", "Magellan", "Christophe Colomb"], r: 3 },
    { q: "Quel est le plus petit pays du monde ?", a: ["Monaco", "Le Vatican", "Malte", "Saint-Marin"], r: 1 },
    { q: "Dans quel pays se trouvent les pyramides de Gizeh ?", a: ["Maroc", "Mexique", "Egypte", "Grece"], r: 2 },
    { q: "Quelle est la monnaie officielle du Royaume-Uni ?", a: ["L'Euro", "Le Dollar", "La Livre Sterling", "Le Yen"], r: 2 },
    { q: "Quel animal est le symbole de la France ?", a: ["L'aigle", "Le lion", "Le coq", "Le loup"], r: 2 },
    { q: "Quel est l'organe principal du systeme circulatoire ?", a: ["Le poumon", "Le cerveau", "Le foie", "Le coeur"], r: 3 },
    { q: "Combien de minutes y a-t-il dans une heure ?", a: ["50", "60", "100", "120"], r: 1 },
    { q: "Qui est le dieu de la foudre dans la mythologie grecque ?", a: ["Poseidon", "Hades", "Zeus", "Apollon"], r: 2 },
    { q: "Quelle est la couleur du cheval blanc d'Henri IV ?", a: ["Noir", "Blanc", "Gris", "Marron"], r: 1 },
    { q: "Dans quelle ville se trouve la tour Eiffel ?", a: ["Londres", "New York", "Paris", "Berlin"], r: 2 },
    { q: "Quel est le plus grand desert du monde ?", a: ["Le Sahara", "Le desert de Gobi", "L'Antarctique", "Le Kalahari"], r: 2 },
    { q: "Quelle langue parle-t-on principalement au Bresil ?", a: ["L'espagnol", "Le portugais", "Le bresilien", "L'anglais"], r: 1 },
    { q: "Quel instrument de musique possede des touches noires et blanches ?", a: ["La guitare", "Le violon", "Le piano", "La flute"], r: 2 },
    { q: "Combien d'Etats y a-t-il aux Etats-Unis ?", a: ["48", "49", "50", "51"], r: 2 },
    { q: "Quel est le sommet le plus haut du monde ?", a: ["Le Mont Blanc", "Le Mont Kilimandjaro", "L'Everest", "Le Mont Fuji"], r: 2 },
    { q: "Qui est l'auteur de la piece 'Romeo et Juliette' ?", a: ["Moliere", "William Shakespeare", "Voltaire", "Arthur Rimbaud"], r: 1 },
    { q: "Quel metal s'attire avec un aimant ?", a: ["Le fer", "L'or", "L'aluminium", "Le cuivre"], r: 0 },
    { q: "Quelle est la capitale de l'Espagne ?", a: ["Barcelone", "Seville", "Madrid", "Valence"], r: 2 },
    { q: "Quel est le plus grand ocean de la Terre ?", a: ["Ocean Indien", "Ocean Atlantique", "Ocean Pacifique", "Ocean Arctique"], r: 2 },
    { q: "Quelle reine a gouverne l'Egypte antique ?", a: ["Cleopatre", "Marie-Antoinette", "Victoria", "Elisabeth Iere"], r: 0 },
    { q: "Quel est le carre de 9 ?", a: ["18", "72", "81", "99"], r: 2 },
    { q: "Quelle est la capitale du Canada ?", a: ["Toronto", "Montreal", "Vancouver", "Ottawa"], r: 3 },
    { q: "Quel scientifique a decouvert la gravite avec une pomme ?", a: ["Albert Einstein", "Isaac Newton", "Galilee", "Louis Pasteur"], r: 1 },
    { q: "Combien de joueurs y a-t-il dans une equipe de football sur le terrain ?", a: ["9", "10", "11", "12"], r: 2 },
    { q: "Quel oiseau ne peut pas voler ?", a: ["L'aigle", "L'autruche", "Le pigeon", "Le moineau"], r: 1 },
    { q: "En quel siecle vivait Louis XIV ?", a: ["XVème", "XVIème", "XVIIème", "XVIIIème"], r: 2 },
    { q: "Quelle est la capitale de l'Italie ?", a: ["Milan", "Venise", "Florence", "Rome"], r: 3 },
    { q: "Quel est l'animal le plus rapide du monde au sol ?", a: ["Le lion", "Le guepard", "Le zebre", "Le lievre"], r: 1 },
    { q: "De quelle couleur est l'emeraude ?", a: ["Bleu", "Rouge", "Vert", "Jaune"], r: 2 },
    { q: "Quel pays a invente les Jeux Olympiques ?", a: ["La Rome antique", "La Grece antique", "L'Egypte", "La Chine"], r: 1 },
    { q: "Quel est le principal ingredient du chocolat ?", a: ["Le lait", "Le sucre", "Le cacao", "La vanille"], r: 2 },
    { q: "Quelle est la capitale de l'Allemagne ?", a: ["Munich", "Francfort", "Berlin", "Hambourg"], r: 2 },
    { q: "Combien d'os un adulte humain possede-t-il environ ?", a: ["106", "206", "306", "406"], r: 1 },
    { q: "Quel sorcier est le heros des livres de J.K. Rowling ?", a: ["Gandalf", "Merlin", "Harry Potter", "Voldemort"], r: 2 },
    { q: "Quel pays est aussi un continent ?", a: ["Le Canada", "L'Australie", "L'Afrique du Sud", "L'Inde"], r: 1 },
    { q: "Quelle est la capitale de la Belgique ?", a: ["Bruges", "Anvers", "Liege", "Bruxelles"], r: 3 },
    { q: "Quelle planete est surnommee la 'Planete Rouge' ?", a: ["Venus", "Mars", "Jupiter", "Saturne"], r: 1 },
    { q: "Quel organe permet aux poissons de respirer sous l'eau ?", a: ["Les poumons", "Les branchies", "Les ecailles", "La peau"], r: 1 },
    { q: "Quel est le symbole chimique de l'eau ?", a: ["CO2", "O2", "H2O", "NaCl"], r: 2 },
    { q: "Combien de couleurs y a-t-il dans l'arc-en-ciel ?", a: ["5", "6", "7", "8"], r: 2 },
    { q: "Quel peintre est celebre pour avoir coupe son oreille ?", a: ["Vincent van Gogh", "Pablo Picasso", "Claude Monet", "Salvador Dali"], r: 0 },
    { q: "Quelle est la capitale des Etats-Unis ?", a: ["New York", "Los Angeles", "Washington D.C.", "Chicago"], r: 2 },
    { q: "Quel est le plus grand os du corps humain ?", a: ["Le radius", "Le femur", "Le tibia", "La colonne vertebrale"], r: 1 },
    { q: "Quel monument se trouve sur la place de l'Etoile a Paris ?", a: ["La Tour Eiffel", "L'Arc de Triomphe", "Le Louvre", "Le Sacre-Coeur"], r: 1 },
    { q: "Quel navire a coule en 1912 apres avoir heurte un iceberg ?", a: ["Le Titanic", "Le Britannic", "Le Santa Maria", "Le Victory"], r: 0 },
    { q: "Quelle est la capitale du Portugal ?", a: ["Porto", "Lisbonne", "Faro", "Madrid"], r: 1 },
    { q: "Combien de coeurs possede une pieuvre ?", a: ["1", "2", "3", "4"], r: 2 },
    { q: "Quel est l'arbre qui donne des glands ?", a: ["Le sapin", "Le chene", "Le bouleau", "Le peuplier"], r: 1 },
    { q: "Quel est le systeme politique de la France actuelle ?", a: ["Monarchie", "Empire", "Republique", "Dictature"], r: 2 },
    { q: "Quel est le pays le plus peuple du monde ?", a: ["Etats-Unis", "Inde", "Chine", "Russie"], r: 1 },
    { q: "Qui a ecrit la fable 'Le Corbeau et le Renard' ?", a: ["Jean de La Fontaine", "Moliere", "Victor Hugo", "Voltaire"], r: 0 },
    { q: "Quelle est la capitale de la Suisse ?", a: ["Zurich", "Geneve", "Berne", "Bale"], r: 2 },
    { q: "Quel est le metal liquide a temperature ambiante ?", a: ["Le plomb", "Le mercure", "Le fer", "Le cuivre"], r: 1 },
    { q: "De quel pays les samourais sont-ils originaires ?", a: ["Chine", "Coree du Sud", "Japon", "Thailande"], r: 2 },
    { q: "Combien de cordes possede generalement une guitare classique ?", a: ["4", "5", "6", "12"], r: 2 },
    { q: "Quelle est la capitale des Pays-Bas ?", a: ["Rotterdam", "La Haye", "Amsterdam", "Utrecht"], r: 2 }
];